name: CI - Minishell

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-dev

      - name: Build project
        run: |
          make

      - name: Verify libft exists
        run: |
          ls -l include/libft
          if [ ! -f include/libft/libft.a ]; then echo "Libft not found"; exit 1; fi

      - name: Verify minishell executable
        run: |
          if [ ! -f ./minishell ]; then echo "Executable not found"; exit 1; fi
          if [ ! -s ./minishell ]; then echo "Executable is empty"; exit 1; fi

      - name: Check permissions for minishell
        run: |
          ls -l ./minishell

      - name: List files in root directory
        run: |
          ls -l

      - name: Check shared library dependencies
        run: |
          ldd ./minishell

      - name: Set PATH and Run minishell
        env:
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
          bash -c "./minishell 2> error.log; if [ $? -ne 0 ]; then cat error.log; fi"
