name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make
      run: make
    - name: Clean
      run: make clean
    - name: Make executable
      run: chmod +x minishell
    - name: Run de program
      run: ./minishell
